trigger: none

resources:
- repo: self

pool: AgentInContainer

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: 'build'
    #     Dockerfile: '$(Build.SourcesDirectory)/Run your Azure DevOps Agent in Kubernetes with Keda/AdoAgentAksDemo/AdoAgentAksDemo/Dockerfile'
    #     buildContext: '$(Build.SourcesDirectory)/Run your Azure DevOps Agent in Kubernetes with Keda/AdoAgentAksDemo'
    #     tags: '$(tag)'

    - task: Bash@3
      displayName: Build Docker Image with Podman
      inputs:
        targetType: inline
        script: |
          podman build -f '$(Build.SourcesDirectory)/Run your Azure DevOps Agent in Kubernetes with Keda/AdoAgentAksDemo/AdoAgentAksDemo/Dockerfile' -t adoagentaksdemo:$(tag) '$(Build.SourcesDirectory)/Run your Azure DevOps Agent in Kubernetes with Keda/AdoAgentAksDemo'