trigger: none

resources:
- repo: self

pool: ManagedDevOpsPoolDemo

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Azure Managed DevOps Pools Explained - A Game Changer for Hosting Agents/DotNetWithDocker/DotNetWithDocker/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/Azure Managed DevOps Pools Explained - A Game Changer for Hosting Agents/DotNetWithDocker'
        tags: '$(tag)'