trigger: none

pool: MDP-VNet-Demo

variables:
  AzureServiceConnection: "AzureServiceConnection" # update with your service connection name
  KeyVaultName: "wolfgangmdpdemokv" # update with your key vault name
  SecretName: "MySecret"

steps:
- checkout: none

- task: AzureCLI@2
  inputs:
    azureSubscription: $(AzureServiceConnection)
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az keyvault secret set --vault-name $(KeyVaultName) --name $(SecretName) --value "This is a secret!"
  displayName: Write secret to key vault
  
- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(AzureServiceConnection)
    KeyVaultName: $(KeyVaultName)
    SecretsFilter: '*'
    RunAsPreJob: false
  displayName: "Read secret from KV"

- task: CmdLine@2
  displayName: Print secret
  inputs:
    script: 'echo $(SecretName) > secrets.txt'

- task: CopyFiles@2
  displayName: Copy file
  inputs:
    Contents: secrets.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'secrets'
    publishLocation: 'Container'