apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesdeploymentdemo
  namespace: default # gitopsdemo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubernetesdeploymentdemo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: kubernetesdeploymentdemo
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: kubernetesdeploymentdemo
        image: wolfgangofner/kubernetesdeploymentdemo:start
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetesdeploymentdemo
  namespace: default # gitopsdemo
  labels:
    name: kubernetesdeploymentdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kubernetesdeploymentdemo
