trigger: none

resources:
- repo: self

pool: Ubuntu-Mdp

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Custom Agent Images for Azure Managed DevOps Pools/MdpCustomImageDemo/MdpCustomImageDemo/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/Custom Agent Images for Azure Managed DevOps Pools/MdpCustomImageDemo'
        tags: '$(Build.BuildId)'