apiVersion: v1
kind: Pod
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  containers:
  - name: whoami
    image: traefik/whoami:latest
    imagePullPolicy: IfNotPresent
  nodeSelector:
    gpu: nvidia