apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 15
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:latest
      topologySpreadConstraints:
      - maxSkew: 2
        topologyKey: kubernetes.io/hostname # Spreads Pods across individual Nodes
        whenUnsatisfiable: ScheduleAnyway # DoNotSchedule (this is the default value)
        labelSelector:
          matchLabels:
            app: whoami