kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store
spec:
  serviceAccountName: $K8sNamespace
  containers:
    - name: busybox
      image: busybox:1.37
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kv-secret-provider"