apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"          
    clientID: $UserAssignedClientId
    keyvaultName: $KeyVaultName
    cloudName: ""                         
    objects:  |
      array:
        - |
          objectName: $KeyVaultSecret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: $TenantId
  secretObjects:                             
  - secretName: newsecret   
    data:
    - key: $KeyVaultSecret                   
      objectName: $KeyVaultSecret                                        
    type: Opaque 