apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: argocd-demo
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: argocd-demo
        image: wolfgangofner/kubernetesdeploymentdemo:start
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: argocd-demo
  labels:
    name: argocd-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: argocd-demo
